name: "Manual Approval Action"
description: "Github Action to pause a workflow until a manual approval is given"
author: "showoffninja"

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  secret:
    description: "github secret"
    required: true
    default: "SomeKindOfSecret"
  approvers:
    description: "Comma separated list of users or teams who can approve the deployment"
    required: true
    default: "primaryApprover"
  minimum-approvals:
    description: "Minimum number of approvals required"
    required: true
    default: 1
  issue-title:
    description: "Title of the issue created for approval"
    required: false
    default: "Manual approval required for workflow run ${{ github.run_id }}"
  issue-body:
    description: "Additional information in the issue created for approval, i.e. link to changed files or docs"
    required: False
    default: "Please approve or deny the deployment of version v1.3.5."
  issue-labels:
    description: "Comma separated list of customized label(s) that can be used to label the issue"
    required: false
    default: "manual-approval"
  exclude-workflow-initiator-as-approver:
    description: "Exclude the workflow initiator as an approver"
    required: true
    default: false
  additional-approved-words:
    description: "Comma separated list of additional words that can be used to approve the deployment"
    required: false
    default: ""
  additional-denied-words:
    description: "Comma separated list of additional words that can be used to deny the deployment"
    required: false
    default: ""

branding:
  icon: "activity"
  color: "green"
