name: "Manual Approval Action"
description: "Github Action to pause a workflow until a manual approval is given"
author: "showoffninja"

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  name:
    description: "The name of the person to greet"
    required: true
    default: "World"

branding:
  icon: "activity"
  color: "green"
