name: Dummy Deployment

on:
  workflow_dispatch:

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Starting pending deployments
        id: Start Deployments
        env: development
