name: Say Hello
on:
  workflow_dispatch:

jobs:
  say_hello:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - uses: ./ # This is the path to the action.yml file
