name: Close Issues

on:
  workflow_dispatch:

jobs:
  comment_on_issue:
    runs-on: ubuntu-latest

    steps:
    - name: comment on issue
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_USER_PAT }}
      run: |
          ISSUE_NUMBER=23
          COMMENT_BODY="Thank you for opening this issue! We will look into it."
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
            -d "{\"body\":\"${COMMENT_BODY}\"}"